export const userConstants = {
  SIGN_IN: 'SIGN_IN',
  SIGN_IN_SUCCESS: 'SIGN_IN_SUCCESS',
  SIGN_IN_FAIL: 'SIGN_IN_FAIL',
  SIGN_OUT: 'SIGN_OUT',
  SIGN_UP: 'SIGN_UP',
  SIGN_UP_SUCCESS: 'SIGN_UP_SUCCESS',
  SIGN_UP_FAIL: 'SIGN_UP_FAIL',
};

export const apiConstants = {
  HOST: 'http://localhost:9090/v0.1.0',
};

export const chatConstants = {
  FETCH_CHAT_ROOMS: 'FETCH_CHAT_ROOMS',
  FETCH_CHAT_ROOMS_SUCCESS: 'FETCH_CHAT_ROOMS_SUCCESS',
  SHOW_SIDEBAR_FORM: 'SHOW_SIDEBAR_FORM',
  HIDE_SIDEBAR_FORM: 'HIDE_SIDEBAR_FORM',
  CREATE_CHAT_ROOM: 'CREATE_CHAT_ROOM',
  CREATE_CHAT_ROOM_SUCCESS: 'CREATE_CHAT_ROOM_SUCCESS',
  CREATE_CHAT_ROOM_FAIL: 'CREATE_CHAT_ROOM_FAIL',
  SELECT_CHAT_ROOM: 'SELECT_CHAT_ROOM',
};
